function initslide() {
	document.writeln("	<div style=\'margin-left: 0px; margin-top: 50px;\'>");
	document.writeln("		<div class=\'leftsidebar_box\'>");
	document.writeln("			<div class=\'line\'></div>");
	document.writeln("			<dl class=\'custom\'>");
	document.writeln("				<dt>");
	document.writeln("					个人信息<img src=\'img/left/select_xl01.png\'>");
	document.writeln("				</dt>");
	document.writeln("				<dd class=\'first_dd\'>");
	document.writeln("					<a href=\'my.html\'>我的信息</a>");
	document.writeln("				</dd>");
	document.writeln("				<dd>");
	document.writeln("					<a href=\'space.html\'>空间使用量</a>");
	document.writeln("				</dd>");
	document.writeln("				<dd>");
	document.writeln("					<a href=\'alterpassword.html\'>修改密码</a>");
	document.writeln("				</dd>");
	document.writeln("			</dl>");
	document.writeln("");
	document.writeln("			<dl class=\'channel\'>");
	document.writeln("				<dt>");
	document.writeln("					全景管理<img src=\'img/left/select_xl01.png\'>");
	document.writeln("				</dt>");
	document.writeln("				<dd class=\'first_dd\'>");
	document.writeln("					<a href=\'myfabu.html\'>我的发布</a>");
	document.writeln("				</dd>");
	document.writeln("				<dd>");
	document.writeln("					<a href=\'mysave.html\'>我的收藏</a>");
	document.writeln("				</dd>");
	document.writeln("				<dd>");
	document.writeln("					<a href=\'panoEdit.html\'>全景编辑</a>");
	document.writeln("				</dd>");
	// document.writeln(" <dd>");
	// document.writeln(" <a href=\'#\'>更改背景音乐</a>");
	// document.writeln(" </dd>");
	document.writeln("			</dl>");
	document.writeln("");
	document.writeln("			<dl class=\'app\'>");
	document.writeln("				<dt onClick=\'changeImage()\'>");
	document.writeln("					消息中心<img src=\'img/left/select_xl01.png\'>");
	document.writeln("				</dt>");
	document.writeln("				<dd class=\'first_dd\'>");
	document.writeln("					<a href=\'commentMessages.html\'>评论消息</a>");
	document.writeln("				</dd>");
	document.writeln("				<dd>");
	document.writeln("					<a href=\'loveMessages.html\'>点赞消息</a>");
	document.writeln("				</dd>");
	//document.writeln("				<dd>");
	//document.writeln("					<a href=\'#\'>系统消息</a>");
	//document.writeln("				</dd>");
	document.writeln("			</dl>");
	document.writeln("			<dl class=\'source\'>");
	document.writeln("				<dt>");
	document.writeln("					素材库管理<img src=\'img/left/select_xl01.png\'>");
	document.writeln("				</dt>");
	document.writeln("				<dd class=\'first_dd\'>");
	document.writeln("					<a href=\'allCoverImg.html\'>封面图片库</a>");
	document.writeln("				</dd>");
	document.writeln("				<dd>");
	document.writeln("					<a href=\'allmusic.html\'>背景音乐库</a>");
	document.writeln("				</dd>");
	document.writeln("			</dl>");
	// document.writeln(" <dl class=\'syetem_management\'>");
	// document.writeln(" <dt>");
	// document.writeln(" 系统管理<img src=\'img/left/select_xl01.png\'>");
	// document.writeln(" </dt>");
	// document.writeln(" <dd class=\'first_dd\'>");
	// document.writeln(" <a href=\'#\'>发布系统消息</a>");
	// document.writeln(" </dd>");
	// document.writeln(" </dl>");

	document.writeln("		</div>");
	document.writeln("	</div>");
}